name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the backend Docker image
      run: docker build -f ./backend/Dockerfile -t ghcr.io/guerric-p/llm-graph-builder-backend:main ./backend && docker push ghcr.io/guerric-p/llm-graph-builder-backend:main
    - name: Build the frontend Docker image
      run: docker build -f ./frontend/Dockerfile -t ghcr.io/guerric-p/llm-graph-builder-frontend:main ./frontend && docker push ghcr.io/guerric-p/llm-graph-builder-frontend:main
